#!/usr/bin/env python3
"""
build_sft_grpo_disjoint.py — split the unified SFT pool into two body-hash
disjoint halves: one for SFT, one for GRPO.

Strategy (option B from our discussion):
  - SFT subset: samples whose NL was originally present in the source corpus
    (high-quality human/scrape comments, no LLM fill)
  - GRPO subset: samples whose NL was generated by an LLM (DS-Coder-V2 fill)

Rationale: SFT loss is sensitive to NL accuracy (cross-entropy on (NL,SVA)
pairs); GRPO with PEC reward is NOT — its reward signal compares the
generated SVA against a known reference SVA, so noisy NL only adds prompt
diversity, not training noise.

Inputs:
  data/train/sft/sft_train_nl_filled_v2.jsonl   (10,931 + 4,483 merged)

Outputs:
  data/train/sft/sft_train_disjoint.jsonl       (~1,845 original-NL records)
  data/train/sft/sft_train_disjoint_L{1..5}.jsonl
  data/train/grpo/grpo_pool_disjoint.jsonl      (~13,569 LLM-filled records)
  data/train/grpo/disjoint_manifest.json

Verifies disjoint by body hash; aborts if any overlap.
"""
import argparse
import hashlib
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

EXPERIMENTS_DIR = Path(__file__).resolve().parent.parent
SFT_DIR = EXPERIMENTS_DIR / "data" / "train" / "sft"
GRPO_DIR = EXPERIMENTS_DIR / "data" / "train" / "grpo"
TEST_DIR = EXPERIMENTS_DIR / "data" / "test"

PLACEHOLDER_RE = re.compile(r"^\s*\[(?:ASSERT|ASSUME|COVER)[^\]]*\]\s*$",
                            re.IGNORECASE)


def body_hash(sva: str) -> str:
    return hashlib.sha256(re.sub(r"\s+", " ", sva).strip().encode()).hexdigest()[:16]


def is_real_nl(nl: str) -> bool:
    nl = (nl or "").strip()
    return len(nl) >= 8 and not PLACEHOLDER_RE.match(nl)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True,
                    help="merged sft_train_nl_filled_v2.jsonl")
    args = ap.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        raise SystemExit(f"missing {in_path}")

    # Load test body hashes for contamination filter
    test_bodies = set()
    for f in [TEST_DIR / "nl2sva_human.jsonl",
              TEST_DIR / "assertionbench.jsonl"]:
        if f.exists():
            for line in open(f):
                test_bodies.add(body_hash(json.loads(line)["reference_sva"]))
    print(f"[guard] test body hashes loaded: {len(test_bodies)}")

    sft_recs = []
    grpo_recs = []
    drop_test = drop_no_nl = drop_no_sva = drop_dup = 0
    seen_hashes = set()

    for line in open(in_path):
        r = json.loads(line)
        ref = (r.get("reference_sva") or "").strip()
        nl = (r.get("nl") or "").strip()
        if not ref:
            drop_no_sva += 1; continue
        if not is_real_nl(nl):
            drop_no_nl += 1; continue
        bh = body_hash(ref)
        if bh in test_bodies:
            drop_test += 1; continue
        if bh in seen_hashes:
            drop_dup += 1; continue
        seen_hashes.add(bh)

        # Route by NL provenance: LLM-filled → GRPO; original → SFT
        record = {
            "id": r.get("id", ""),
            "nl": nl,
            "reference_sva": ref,
            "expected_tcl": int(r.get("expected_tcl", 0)),
            "rtl_context": r.get("rtl_context", ""),
            "source": r.get("source", ""),
            "hash": bh,
        }
        if r.get("nl_filled_by"):
            record["nl_filled_by"] = r["nl_filled_by"]
            grpo_recs.append(record)
        else:
            sft_recs.append(record)

    print(f"[filter] drops: test={drop_test} no_NL={drop_no_nl} "
          f"no_SVA={drop_no_sva} dup={drop_dup}")
    print(f"[split]  SFT (original NL):   {len(sft_recs)}")
    print(f"[split]  GRPO (LLM-filled NL): {len(grpo_recs)}")

    # Verify body-hash disjoint
    sft_hashes = {r["hash"] for r in sft_recs}
    grpo_hashes = {r["hash"] for r in grpo_recs}
    overlap = sft_hashes & grpo_hashes
    if overlap:
        raise SystemExit(f"DISJOINT VIOLATION: {len(overlap)} overlap")
    print(f"[verify] SFT ∩ GRPO = 0 ✓")

    # Write SFT
    SFT_DIR.mkdir(parents=True, exist_ok=True)
    with open(SFT_DIR / "sft_train_disjoint.jsonl", "w") as f:
        for r in sft_recs:
            f.write(json.dumps(r) + "\n")
    sft_per_tcl = Counter(r["expected_tcl"] for r in sft_recs)
    by_lvl = defaultdict(list)
    for r in sft_recs:
        by_lvl[r["expected_tcl"]].append(r)
    for lvl in (1, 2, 3, 4, 5):
        with open(SFT_DIR / f"sft_train_disjoint_L{lvl}.jsonl", "w") as f:
            for r in by_lvl.get(lvl, []):
                f.write(json.dumps(r) + "\n")

    # Write GRPO
    GRPO_DIR.mkdir(parents=True, exist_ok=True)
    with open(GRPO_DIR / "grpo_pool_disjoint.jsonl", "w") as f:
        for r in grpo_recs:
            f.write(json.dumps(r) + "\n")
    grpo_per_tcl = Counter(r["expected_tcl"] for r in grpo_recs)

    print(f"\nSFT per-TCL:  " + "  ".join(
        f"L{l}={sft_per_tcl.get(l, 0)}" for l in (1, 2, 3, 4, 5)))
    print(f"GRPO per-TCL: " + "  ".join(
        f"L{l}={grpo_per_tcl.get(l, 0)}" for l in (1, 2, 3, 4, 5)))

    # Manifest
    manifest = {
        "policy": "Body-hash disjoint split. SFT = original-NL records, "
                  "GRPO = LLM-filled-NL records. SFT loss = CE on (NL,SVA), "
                  "GRPO reward = PEC equivalence to reference SVA (NL accuracy "
                  "doesn't enter the reward signal).",
        "input": str(in_path),
        "sft_size": len(sft_recs),
        "grpo_size": len(grpo_recs),
        "sft_per_tcl": dict(sft_per_tcl),
        "grpo_per_tcl": dict(grpo_per_tcl),
        "drops": {"test_overlap": drop_test, "no_NL": drop_no_nl,
                  "no_SVA": drop_no_sva, "duplicate": drop_dup},
        "intersection_check": "PASS (body hashes disjoint by construction)",
    }
    with open(GRPO_DIR / "disjoint_manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"\nManifest: {GRPO_DIR / 'disjoint_manifest.json'}")


if __name__ == "__main__":
    main()
